oauth:
  kakao:
    name: "kakaoOAuth"
    url: "https://kapi.kakao.com/v2/user/me"
  naver:
    name: "naverOAuth"
    url: "https://openapi.naver.com/v1/nid/me"

oauth2:
  kakao:
    name: "kakaoOAuth"
    url: "https://kapi.kakao.com/v2/user/me"
  naver:
    name: "naverOAuth"
    url: "https://openapi.naver.com/v1/nid/me"
  jwt:
    token-secret: "asdf"
    access-token-expire-time: 1
    bearer-prefix: "Bearer"
    authority-key: "Role"
    refresh-token-expire-time: 15
    access-token-header: "access_token"